; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
; FAMISTUDIO_USE_VOLUME_TRACK = 1

music_data_creek:
	db 1
	dw @instruments
	dw @samples-4
; 00 : creek
	dw @song0ch0
	dw @song0ch1
	dw @song0ch2
	dw @song0ch3
	dw @song0ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env3,@env5,@env9,@env4 ; 00 : Banjo
	dw @env10,@env5,@env2,@env1 ; 01 : Acoustic Bass
	dw @env7,@env5,@env2,@env6 ; 02 : Acoustic Guitar (steel)

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$c0,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$00,$08
@env2:
	db $c3,$7f,$00,$00
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $00,$c0,$04,$c1,$c0,$c1,$00,$05
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $00,$c0,$c0,$c1,$c3,$c4,$c3,$c1,$c0,$00,$08
@env7:
	db $00,$c7,$7f,$00,$02
@env8:
	db $7f,$00,$00
@env9:
	db $c1,$7f,$00,$00
@env10:
	db $00,$c8,$7f,$00,$02

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

@song0ch0:
	db $bb, $48, $9b, $7b, $80
@song0ref6:
	db $16, $97, $00, $11, $97, $00, $0e, $95, $00, $7a, $16, $89, $00, $7b, $0f, $89, $00, $13, $89, $00, $7a, $16, $89, $00
	db $7b, $11, $97, $00, $11
@song0ref35:
	db $95, $00
@song0ref37:
	db $48
@song0ref38:
	db $0c, $8b, $0e, $8b, $7a, $16, $8b, $7b, $11, $8b, $0c, $8b, $0e, $8b, $05, $8b, $11, $89, $07, $8b, $0e, $8b, $11, $8b
	db $7a, $16, $8b, $7b, $0a, $97, $00, $7d, $16, $97, $48, $97, $00, $81, $7b
	db $41, $0a
	dw @song0ref6
@song0ref80:
	db $8b, $7b, $0f, $8b, $13, $8b, $7a, $16, $8b, $7b, $11, $97, $00, $16
	db $41, $16
	dw @song0ref35
	db $7d, $11, $8b, $7a, $16, $8b, $7b, $0a, $97, $00, $16, $97
	db $41, $0c
	dw @song0ref37
@song0ref112:
	db $7a, $16, $8b, $7b, $11, $89, $0c, $8b, $0e, $8b, $7a, $16, $8b, $7b, $11, $8b, $05, $97, $00, $11, $97
	db $41, $0c
	dw @song0ref37
@song0ref136:
	db $07, $8b, $11, $89, $05, $8b, $0e, $8b, $7a, $16, $8b, $7b, $11, $8b, $0a, $97, $00, $16, $97
	db $41, $0c
	dw @song0ref37
	db $41, $0f
	dw @song0ref112
	db $16, $97
	db $41, $0c
	dw @song0ref37
	db $41, $0f
	dw @song0ref136
	db $11, $97
@song0ref171:
	db $48, $0a, $97, $00, $16
@song0ref176:
	db $89, $00, $8d, $0e, $97, $00, $11
@song0ref183:
	db $89, $00, $8b, $0f, $97, $00, $13, $89, $00, $8d, $1a
@song0ref194:
	db $89, $00, $8d, $0e, $95, $00
@song0ref200:
	db $48, $0a, $89, $00, $11, $89, $00, $16, $89, $00, $0c, $89, $00, $11, $89, $00, $0a, $89, $00, $07, $89, $00, $11, $87
	db $00, $05, $89, $00, $0a, $89, $00, $09, $97, $00, $0a, $97, $00, $07, $95, $00, $48, $0a, $97, $00, $0e
	db $41, $11
	dw @song0ref176
	db $11
	db $41, $30
	dw @song0ref194
	db $16, $89, $00, $a9, $16, $89, $00, $a7, $0e, $89, $00, $a9, $0e, $89, $00, $8b
	db $41, $2a
	dw @song0ref200
	db $16, $89, $00, $a9, $16
@song0ref276:
	db $89, $00, $a7, $16, $89, $00, $a9, $16, $89, $00, $8b
	db $41, $25
	dw @song0ref200
	db $8b, $16, $89
	db $41, $11
	dw @song0ref171
	db $1b, $89, $00, $8d, $16
	db $41, $30
	dw @song0ref194
	db $16, $89, $00, $8d, $0e, $97, $00, $1a
	db $41, $0a
	dw @song0ref183
	db $11
	db $41, $30
	dw @song0ref194
	db $11, $89, $00, $a9, $0e
	db $41, $0b
	dw @song0ref276
	db $41, $2a
	dw @song0ref200
	db $11, $89, $00, $a9, $0e, $89, $00, $a7, $0e, $89, $00, $a9, $16, $89, $00, $8b
	db $41, $25
	dw @song0ref200
	db $8b, $16, $89, $48, $8d, $00, $8b
	db $41, $18
	dw @song0ref6
	db $7a, $16, $95, $00, $48, $7b
	db $41, $1b
	dw @song0ref38
	db $16, $97, $48, $97, $00, $81
	db $41, $0a
	dw @song0ref6
	db $41, $0b
	dw @song0ref80
	db $41, $1d
	dw @song0ref35
	db $16, $97
	db $41, $0c
	dw @song0ref37
	db $41, $11
	dw @song0ref112
	db $41, $0c
	dw @song0ref37
	db $41, $0f
	dw @song0ref136
	db $11, $97
	db $41, $0c
	dw @song0ref37
	db $41, $11
	dw @song0ref112
@song0ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid)
	db $41, $0c
	dw @song0ref38
	db $41, $0f
	dw @song0ref136
	db $99, $42
	dw @song0ch0loop
@song0ch1:
	db $bb, $7b, $82, $0a, $8b, $00, $a7
@song0ref426:
	db $05, $8b, $00, $a5, $03
@song0ref431:
	db $8b, $00, $a7, $40, $0a, $8b, $00, $a5, $0a, $8b, $00, $a7, $07, $8b, $00, $a5, $05
	db $41, $0b
	dw @song0ref431
	db $41, $10
	dw @song0ref426
	db $05, $8b, $00, $a5, $40, $0c
	db $41, $0b
	dw @song0ref431
@song0ref463:
	db $05, $8b, $00, $a5, $0a, $8b, $00, $a7, $05, $8b, $00, $a5
@song0ref475:
	db $0a, $8b, $00, $a7, $05, $8b, $00, $a5, $40, $0c
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref463
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref426
	db $41, $0b
	dw @song0ref431
	db $41, $10
	dw @song0ref426
	db $05, $8b, $00, $a5, $40, $0c
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref463
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref463
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref426
	db $41, $0b
	dw @song0ref431
	db $41, $10
	dw @song0ref426
	db $05, $8b, $00, $a5, $40, $0c
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref463
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref463
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref426
	db $41, $0b
	dw @song0ref431
	db $41, $10
	dw @song0ref426
	db $05, $8b, $00, $a5, $40, $0c
	db $41, $0b
	dw @song0ref431
	db $41, $15
	dw @song0ref463
	db $41, $0b
	dw @song0ref431
	db $41, $0c
	dw @song0ref463
@song0ch1loop:
	db $41, $09
	dw @song0ref475
	db $8b, $00, $a7, $40, $0a, $8b, $00, $a5, $42
	dw @song0ch1loop
@song0ch2:
	db $bb, $9b, $84, $22
@song0ref600:
	db $99, $00, $99
@song0ref603:
	db $26, $97, $00, $99, $27, $99, $00, $99, $1d
@song0ref612:
	db $97, $00, $99, $26
@song0ref616:
	db $99, $00, $99, $22
@song0ref620:
	db $97, $00, $99, $18
@song0ref624:
	db $99, $00, $99, $26
@song0ref628:
	db $97
@song0ref629:
	db $00, $99, $26, $99, $00, $99, $1a
@song0ref636:
	db $97, $00, $99, $1b
@song0ref640:
	db $99, $00, $99, $1a, $97, $00, $99, $26
@song0ref648:
	db $99, $00, $99
@song0ref651:
	db $1d, $97, $00, $99, $24
@song0ref656:
	db $99, $00, $99, $22
@song0ref660:
	db $97, $00, $99, $1a, $99, $00, $99, $26, $97, $00, $99, $1d
	db $41, $0b
	dw @song0ref656
	db $22
	db $41, $0b
	dw @song0ref636
@song0ref679:
	db $22, $99, $00, $99, $1a, $97, $00, $99, $1a, $99, $00, $99, $22, $97, $00, $99, $1d
	db $41, $0b
	dw @song0ref616
	db $22, $97, $00, $99, $1d
	db $41, $0b
	dw @song0ref600
	db $1a
	db $41, $0b
	dw @song0ref612
	db $1b
@song0ref712:
	db $99, $00, $99, $1a
@song0ref716:
	db $97, $00, $99, $22, $99, $00, $99, $1d, $97, $00, $99
	db $41, $0c
	dw @song0ref679
	db $41, $10
	dw @song0ref651
	db $1d
@song0ref734:
	db $97, $00, $99
@song0ref737:
	db $22
@song0ref738:
	db $99, $00, $99, $1a, $97, $00, $99, $1d, $99, $00, $99, $1a
	db $41, $0b
	dw @song0ref620
	db $1a, $99, $00, $99, $1d, $97, $00, $99, $22
	db $41, $0b
	dw @song0ref624
	db $26, $97, $00, $99, $1b
	db $41, $0b
	dw @song0ref624
	db $41, $0c
	dw @song0ref603
	db $22, $99, $00, $99, $22, $97, $00, $99, $24, $99, $00, $99, $1d
	db $41, $0b
	dw @song0ref660
	db $1b
	db $41, $0b
	dw @song0ref738
	db $26, $97, $00, $99, $1b, $99, $00, $99, $26
	db $41, $0b
	dw @song0ref660
	db $41, $0c
	dw @song0ref737
	db $22, $97, $00, $99, $24, $99, $00, $99, $26
	db $41, $0b
	dw @song0ref716
	db $26
	db $41, $0b
	dw @song0ref640
	db $26, $97, $00, $99, $24, $99, $00, $99, $26
	db $41, $0b
	dw @song0ref734
	db $1f
	db $41, $0f
	dw @song0ref712
	db $24, $99, $00, $99, $26
	db $41, $0b
	dw @song0ref660
	db $41, $10
	dw @song0ref679
	db $21
	db $41, $0b
	dw @song0ref656
	db $1a
	db $41, $0b
	dw @song0ref628
	db $22
	db $41, $0b
	dw @song0ref648
	db $26, $97, $00, $99, $1a
	db $41, $0d
	dw @song0ref640
@song0ch2loop:
	db $41, $0a
	dw @song0ref629
	db $21, $89, $00, $8d, $26, $89, $00, $a7, $42
	dw @song0ch2loop
@song0ch4:
@song0ch3:
	db $bb
@song0ref891:
	db $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db
	db $41, $0a
	dw @song0ref891
	db $41, $0a
	dw @song0ref891
	db $41, $0a
	dw @song0ref891
	db $41, $0a
	dw @song0ref891
	db $41, $0a
	dw @song0ref891
	db $ff, $db
@song0ch3loop:
	db $ff, $db, $42
	dw @song0ch3loop
