; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
; FAMISTUDIO_USE_VOLUME_TRACK = 1

music_data_untitled:
	db 2
	dw @instruments
	dw @samples-4
; 00 : maggie
	dw @song0ch0
	dw @song0ch1
	dw @song0ch2
	dw @song0ch3
	dw @song0ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0
; 01 : creek
	dw @song1ch0
	dw @song1ch1
	dw @song1ch2
	dw @song1ch3
	dw @song1ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env3,@env6,@env8,@env0 ; 00 : Harmonica
	dw @env7,@env6,@env8,@env1 ; 01 : Acoustic Bass
	dw @env3,@env6,@env8,@env5 ; 02 : Banjo
	dw @env2,@env6,@env9,@env4 ; 03 : Acoustic Guitar (steel)

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$c0,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$00,$08
@env2:
	db $00,$c5,$7f,$00,$02
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $00,$c0,$c0,$c1,$c2,$c1,$c2,$c1,$c0,$00,$08
@env5:
	db $00,$c0,$04,$c1,$c0,$c1,$00,$05
@env6:
	db $c0,$7f,$00,$01
@env7:
	db $00,$c4,$7f,$00,$02
@env8:
	db $7f,$00,$00
@env9:
	db $c1,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

@song0ch0:
	db $80
@song0ref2:
	db $25, $c9, $00, $22, $b5, $00, $20, $8f, $00, $1e, $c7, $00, $20, $b5, $00, $1e, $8f, $00, $1e, $ff, $95, $00, $1b, $a3
	db $00, $1e, $c7, $00, $1b, $a3, $00, $48, $19, $c9, $00, $1e, $c9, $00, $22, $c7, $00, $25, $c9, $00, $20, $ff, $e3, $00
	db $25, $c9, $00, $48
	db $41, $20
	dw @song0ref2
	db $b5, $00, $19, $8f, $00, $1e, $a1, $00, $22, $a3
@song0ref67:
	db $00, $25, $c7, $00, $20, $b5, $00, $22, $8f, $00, $1e, $ff, $e3, $00, $1e, $c9, $00, $48, $27, $c9, $00, $27, $b5, $00
	db $27, $8f, $00, $23, $c7, $00, $25, $b5, $00, $27, $8f, $00, $25, $ff, $95, $00, $22, $a3, $00, $25, $c7, $00, $22, $a3
	db $00, $48, $20, $ef, $00, $25, $a3, $00, $25, $a1, $00, $24, $a1, $00, $29, $a3, $00, $27, $a1, $00, $25, $ff, $e3, $00
	db $25, $c9, $00, $48
	db $41, $20
	dw @song0ref2
	db $b5, $00, $19, $8f, $00, $1e, $b5, $00, $22, $8f
	db $41, $0c
	dw @song0ref67
	db $ff, $b1, $00
@song0ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $19, $b5, $00, $19, $8f, $00, $1e, $b5, $00, $22, $8f
	db $41, $0e
	dw @song0ref67
	db $cd
@song0ref181:
	db $48, $ff, $ff, $ff, $ff, $eb, $48, $ff, $ff, $ff, $ff, $eb, $48, $ff, $ff, $ff, $ff, $eb
	db $41, $0f
	dw @song0ref181
	db $41, $0e
	dw @song0ref181
	db $9d
@song0ref206:
	db $27, $c9
@song0ref208:
	db $00, $48, $27, $c9, $00, $24, $b5, $00, $22, $8f, $00, $20, $c7, $00, $22, $b5, $00, $20, $8f, $00, $20, $ff, $95, $00
	db $1d, $a3, $00, $20, $c7, $00, $1d, $a3, $00, $48, $1b, $c9, $00, $20, $a1, $00, $20, $a3, $00, $24, $c7, $00, $27, $c9
	db $00, $22, $ff, $e3, $00
	db $41, $23
	dw @song0ref206
	db $b5, $00, $1b, $8f, $00, $20, $a1, $00, $24, $a3
@song0ref274:
	db $00, $27, $c7, $00, $22, $b5, $00, $24, $8f, $00, $20, $ff, $e3, $00, $20, $c9, $00, $48, $29, $c9, $00, $29, $b5, $00
	db $29, $8f, $00, $25, $c7, $00, $27, $b5, $00, $29, $8f, $00, $27, $ff, $95, $00, $24, $a3, $00, $27, $c7, $00, $24, $a3
	db $00, $48, $22, $c9, $00, $27, $a1
@song0ref329:
	db $00, $27, $a3, $00, $27, $a1, $00, $26, $a1, $00, $2b, $a3, $00, $29, $a1, $00, $27, $ff, $e3, $00, $27, $a1, $00, $27
	db $a3
	db $41, $21
	dw @song0ref208
	db $b5, $00, $1b, $8f, $00, $20, $b5, $00, $24, $8f
	db $41, $31
	dw @song0ref274
	db $ef
	db $41, $19
	dw @song0ref329
	db $41, $21
	dw @song0ref208
	db $b5, $00, $1b, $8f, $00, $20, $b5, $00, $24, $8f
	db $41, $0c
	dw @song0ref274
	db $ff, $b1, $00, $48, $1b, $b5, $00, $1b, $8f, $00, $20, $b5, $00, $24, $8f
	db $41, $0c
	dw @song0ref274
	db $ff, $b3, $48, $ff, $e5, $00, $ff, $ff, $ff, $83, $42
	dw @song0ch0loop
@song0ch1:
	db $82
@song0ref422:
	db $06, $c9, $00, $01, $b5, $00, $01, $8f, $00, $06, $a1, $00, $06, $a1, $00, $08, $a3, $00, $0a, $a1, $00, $0b, $c9, $00
	db $06, $c7, $00, $0b, $c9, $00, $06, $c9, $00, $0d, $c9, $00, $0a, $c9, $00, $06, $c7, $00, $01, $c9, $00, $0d, $c9, $00
	db $01, $b5, $00, $01
@song0ref474:
	db $8d, $00
@song0ref476:
	db $0d, $a3, $00, $01, $a1, $00, $03, $a1, $00, $05, $a3, $00
	db $41, $24
	dw @song0ref422
@song0ref491:
	db $01, $b5, $00, $01
@song0ref495:
	db $8f, $00, $0d, $a1, $00, $01, $a1
@song0ref502:
	db $00, $03, $a3, $00, $05, $a1, $00, $06, $c9, $00, $01, $c7, $00, $06, $b5, $00, $06, $8f, $00, $08, $a1, $00, $0a, $a3
	db $00, $0b, $c9, $00, $06, $c9, $00, $0f, $b5, $00, $0f, $8d
	db $41, $0e
	dw @song0ref502
@song0ref541:
	db $c9, $00, $01, $c9, $00, $0d, $c9, $00, $08, $b5, $00, $08, $8f, $00, $03
@song0ref556:
	db $a1, $00, $08, $a1, $00, $0a, $a3, $00, $0c, $a1, $00, $0d, $c9, $00, $08, $b5, $00, $08
	db $41, $0e
	dw @song0ref474
	db $41, $24
	dw @song0ref422
	db $06, $b5, $00, $06
	db $41, $15
	dw @song0ref495
	db $c9, $00, $01, $c9, $00
@song0ch1loop:
	db $0d, $c9, $00, $06, $b5, $00, $06
	db $41, $14
	dw @song0ref495
	db $41, $0c
	dw @song0ref476
	db $41, $42
	dw @song0ref422
	db $41, $24
	dw @song0ref422
	db $41, $2f
	dw @song0ref491
	db $41, $0e
	dw @song0ref502
	db $41, $21
	dw @song0ref541
	db $41, $0e
	dw @song0ref474
	db $41, $24
	dw @song0ref422
	db $06, $b5, $00, $06
	db $41, $15
	dw @song0ref495
	db $c9, $00, $01, $c9, $00, $0d, $c9, $00, $06, $b5, $00, $06
	db $41, $14
	dw @song0ref495
	db $07
@song0ref650:
	db $a3, $00, $03, $a1, $00, $05, $a1, $00, $07, $a3, $00, $08, $c9, $00, $03, $b5, $00, $03, $8f, $00, $08
	db $41, $0f
	dw @song0ref556
@song0ref674:
	db $c7, $00, $0d, $c9, $00, $08, $c9, $00, $0f, $c9, $00, $0c, $c9, $00, $08, $c7, $00, $03, $c9, $00, $0f, $c9, $00, $03
	db $b5, $00, $03, $8d, $00, $0f
	db $41, $15
	dw @song0ref650
	db $41, $0f
	dw @song0ref556
	db $41, $0b
	dw @song0ref674
	db $03, $b5, $00, $03
@song0ref717:
	db $8f, $00, $0f, $a1, $00, $03, $a1
@song0ref724:
	db $00, $05, $a3, $00, $07, $a1, $00, $08, $c9, $00, $03, $c7, $00, $08, $b5, $00, $08, $8f
@song0ref742:
	db $00, $0a, $a1, $00, $0c, $a3, $00, $0d, $c9, $00, $08, $c9, $00, $11, $b5, $00, $11, $8d
	db $41, $0e
	dw @song0ref724
@song0ref763:
	db $c9, $00, $03, $c9, $00, $0f, $c9, $00, $0a, $b5, $00, $0a, $8f, $00, $05, $a1, $00, $0a, $a1, $00, $0c, $a3, $00, $0e
	db $a1, $00, $0f, $c9, $00, $0a, $b5, $00, $0a, $8d, $00, $0f
	db $41, $15
	dw @song0ref650
	db $41, $0f
	dw @song0ref556
	db $41, $0b
	dw @song0ref674
	db $08, $b5, $00, $08
	db $41, $15
	dw @song0ref717
	db $a3, $00, $08, $a1
	db $41, $12
	dw @song0ref742
	db $41, $0e
	dw @song0ref724
	db $41, $24
	dw @song0ref763
	db $41, $15
	dw @song0ref650
	db $41, $0f
	dw @song0ref556
	db $41, $0b
	dw @song0ref674
	db $08, $b5, $00, $08
	db $41, $15
	dw @song0ref717
	db $c9, $00, $03, $c9, $00, $0f, $c9, $00, $08, $b5, $00, $08
	db $41, $15
	dw @song0ref717
	db $c9, $00, $03, $c9, $00, $08, $c9, $00, $03, $c9, $00, $08, $ff, $95, $00, $ff, $ff, $b5, $42
	dw @song0ch1loop
@song0ch2:
	db $80
@song0ref881:
	db $2a, $c9, $00, $25, $b5, $00, $23, $8f, $00, $22, $c7, $00, $23, $b5, $00, $22, $8f, $00, $23, $ff, $95, $00, $23, $a3
	db $00, $23, $c7, $00, $23, $a3, $00, $22, $c9, $00, $22, $c9, $00, $25, $c7, $00, $2a, $c9, $00, $23, $ff, $e3, $00, $29
	db $c9, $00
	db $41, $20
	dw @song0ref881
	db $b5, $00, $22, $8f, $00, $25, $a1, $00, $25, $a3
@song0ref944:
	db $00, $2a, $c7, $00, $23, $b5, $00, $25, $8f, $00, $22, $ff, $e3, $00, $22, $c9, $00, $2a, $c9, $00, $2a, $b5, $00, $2a
	db $8f, $00, $27, $c7, $00, $29, $b5, $00, $2a, $8f, $00, $2a, $ff, $95, $00, $25, $a3, $00, $2a, $c7, $00, $25, $a3, $00
	db $29, $ef, $00, $29, $a3, $00, $29, $a1, $00, $27, $a1, $00, $2c, $a3, $00, $2a, $a1, $00, $29, $ff, $e3, $00, $29, $c9
	db $00
	db $41, $23
	dw @song0ref881
	db $b5, $00, $25, $8f
	db $41, $0c
	dw @song0ref944
	db $ff, $b1, $00
@song0ch2loop:
	db $22, $c9, $00, $22, $b5, $00, $25, $8f
	db $41, $0e
	dw @song0ref944
	db $cd
@song0ref1043:
	db $ff, $ff, $ff, $ff, $eb, $ff, $ff, $ff, $ff, $eb, $ff, $ff, $ff, $ff, $eb
	db $41, $0f
	dw @song0ref1043
	db $41, $0e
	dw @song0ref1043
	db $9d
@song0ref1065:
	db $2b, $c9
@song0ref1067:
	db $00, $2c, $c9, $00, $27, $b5, $00, $25, $8f, $00, $24, $c7, $00, $25, $b5, $00, $24, $8f, $00, $25, $ff, $95, $00, $25
	db $a3, $00, $25, $c7, $00, $25, $a3, $00, $24, $c9, $00, $24, $a1, $00, $24, $a3, $00, $27, $c7, $00, $2c, $c9, $00, $25
	db $ff, $e3, $00
	db $41, $23
	dw @song0ref1065
	db $b5, $00, $24, $8f, $00, $27, $a1, $00, $27, $a3
@song0ref1131:
	db $00, $2c, $c7, $00, $25, $b5, $00, $27, $8f, $00, $24, $ff, $e3, $00, $24, $c9, $00, $2c, $c9, $00, $2c, $b5, $00, $2c
	db $8f, $00, $29, $c7, $00, $2b, $b5, $00, $2c, $8f, $00, $2c, $ff, $95, $00, $27, $a3, $00, $2c, $c7, $00, $27, $a3, $00
	db $2b, $c9, $00, $2b, $a1
@song0ref1184:
	db $00, $2b, $a3, $00, $2b, $a1, $00, $29, $a1, $00, $2e, $a3, $00, $2c, $a1, $00, $2b, $ff, $e3, $00, $2b, $a1, $00, $2b
	db $a3
	db $41, $24
	dw @song0ref1067
	db $b5, $00, $27, $8f
	db $41, $31
	dw @song0ref1131
	db $ef
	db $41, $19
	dw @song0ref1184
	db $41, $24
	dw @song0ref1067
	db $b5, $00, $27, $8f
	db $41, $0c
	dw @song0ref1131
	db $ff, $b1, $00, $24, $c9, $00, $24, $b5, $00, $27, $8f
	db $41, $0c
	dw @song0ref1131
	db $ff, $b3, $ff, $e5, $00, $ff, $ff, $ff, $83, $42
	dw @song0ch2loop
@song0ch4:
@song0ch3:
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $ff, $ff, $ff, $ff, $eb, $ff, $ff, $ff, $ff, $eb
@song0ch3loop:
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $41, $0f
	dw @song0ref1043
	db $42
	dw @song0ch3loop
@song1ch0:
@song1ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $9b, $7b, $84
@song1ref8:
	db $16, $97, $00, $11, $97, $00, $0e, $95, $00, $7a, $16, $89, $00, $7b, $0f, $89, $00, $13, $89, $00, $7a, $16, $89, $00
	db $7b, $11
@song1ref34:
	db $97, $00
@song1ref36:
	db $11
@song1ref37:
	db $95, $00, $48
@song1ref40:
	db $0c, $89, $00, $0e, $89, $00, $7a, $16, $89, $00, $7b, $11, $89, $00, $0c, $89, $00, $0e, $89, $00, $05, $89, $00, $11
	db $87, $00, $07, $89, $00, $0e, $89, $00, $11, $89, $00, $7a, $16, $89, $00, $7b, $0a, $97, $00, $7d, $16, $97, $48, $97
	db $00, $81, $7b
	db $41, $18
	dw @song1ref8
	db $16
	db $41, $20
	dw @song1ref37
	db $7d, $11, $89, $00, $7a, $16, $89, $00, $7b, $0a, $97, $00, $16
	db $41, $14
	dw @song1ref37
@song1ref114:
	db $7a, $16, $89, $00, $7b, $11, $87, $00, $0c, $89, $00, $0e, $89, $00, $7a, $16, $89, $00, $7b, $11, $89, $00, $05
	db $41, $17
	dw @song1ref34
@song1ref140:
	db $07, $89, $00, $11, $87, $00, $05, $89, $00, $0e, $89, $00, $7a, $16, $89, $00, $7b, $11, $89, $00, $0a, $97, $00, $16
	db $41, $14
	dw @song1ref37
	db $41, $13
	dw @song1ref114
	db $97, $00, $16
	db $41, $14
	dw @song1ref37
	db $41, $15
	dw @song1ref140
	db $11, $95
@song1ref181:
	db $00, $48, $0a, $97, $00, $16
@song1ref187:
	db $89, $00, $8d, $0e, $97, $00, $11, $89, $00, $8b, $0f, $97, $00, $13, $89, $00, $8d, $1a
@song1ref205:
	db $89, $00, $8d, $0e, $95, $00
@song1ref211:
	db $48, $0a, $89, $00, $11, $89, $00, $16, $89, $00, $0c, $89, $00, $11, $89, $00, $0a, $89, $00, $07, $89, $00, $11, $87
	db $00, $05, $89, $00, $0a, $89, $00, $09, $97, $00, $0a, $97, $00, $07, $95, $00, $48, $0a, $97, $00, $0e
	db $41, $11
	dw @song1ref187
	db $11
	db $41, $30
	dw @song1ref205
	db $16, $89, $00, $a9, $16, $89, $00, $a7, $0e, $89, $00, $a9, $0e, $89, $00, $8b
	db $41, $2a
	dw @song1ref211
	db $16, $89, $00, $a9, $16, $89, $00, $a7, $16, $89, $00, $a9, $16, $89, $00, $8b
	db $41, $25
	dw @song1ref211
	db $89, $00, $16, $87
	db $41, $12
	dw @song1ref181
	db $1b, $89, $00, $8d, $16
	db $41, $30
	dw @song1ref205
	db $16, $89, $00, $8d, $0e, $97, $00, $1a, $89, $00, $8b, $0f, $97, $00, $13, $89, $00, $8d, $11
	db $41, $30
	dw @song1ref205
	db $11, $89, $00, $a9, $0e, $89, $00, $a7, $16, $89, $00, $a9, $16, $89, $00, $8b
	db $41, $2a
	dw @song1ref211
	db $11, $89, $00, $a9, $0e, $89, $00, $a7, $0e, $89, $00, $a9, $16, $89, $00, $8b
	db $41, $25
	dw @song1ref211
	db $89, $00, $16, $87, $00, $48, $9b
	db $41, $18
	dw @song1ref8
	db $7a, $16, $95, $00, $48, $7b
	db $41, $27
	dw @song1ref40
	db $16, $97, $48, $97, $00, $81
	db $41, $18
	dw @song1ref8
	db $16
	db $41, $29
	dw @song1ref37
	db $16
	db $41, $14
	dw @song1ref37
	db $41, $13
	dw @song1ref114
	db $41, $17
	dw @song1ref34
	db $41, $15
	dw @song1ref140
	db $41, $15
	dw @song1ref36
	db $41, $13
	dw @song1ref114
	db $41, $17
	dw @song1ref34
	db $41, $15
	dw @song1ref140
	db $99, $42
	dw @song1ch0loop
@song1ch1:
@song1ch1loop:
	db $7b, $86
@song1ref440:
	db $0a, $99, $00, $99, $05, $99, $00, $97
@song1ref448:
	db $03, $99, $00, $99, $40, $0a, $99, $00, $97, $0a, $99, $00, $99, $07, $99, $00, $97, $05, $99, $00, $99, $40, $0a, $99
	db $00, $97
	db $41, $14
	dw @song1ref440
@song1ref477:
	db $05, $99, $00, $97, $40, $0c, $99, $00, $99, $40, $0a, $99, $00, $97, $0a, $99, $00, $99, $05, $99, $00, $97, $0a, $99
	db $00, $99, $05, $99, $00, $97, $0a, $99, $00, $99
	db $41, $20
	dw @song1ref477
	db $41, $14
	dw @song1ref477
	db $41, $18
	dw @song1ref448
	db $41, $14
	dw @song1ref440
	db $41, $20
	dw @song1ref477
	db $41, $20
	dw @song1ref477
	db $41, $14
	dw @song1ref477
	db $41, $18
	dw @song1ref448
	db $41, $14
	dw @song1ref440
	db $41, $20
	dw @song1ref477
	db $41, $20
	dw @song1ref477
	db $41, $14
	dw @song1ref477
	db $41, $18
	dw @song1ref448
	db $41, $14
	dw @song1ref440
	db $41, $20
	dw @song1ref477
	db $41, $20
	dw @song1ref477
	db $05, $99, $00, $97, $40, $0c, $99, $00, $99, $40, $0a, $99, $00, $97, $42
	dw @song1ch1loop
@song1ch2:
@song1ch2loop:
	db $ff, $db, $ff, $db, $82, $26, $8b, $00, $a7, $1a, $8b, $00, $a5, $1b, $8b, $00, $a7, $1a, $8b, $00, $a5, $26, $8b, $00
	db $a7
@song1ref602:
	db $1d, $8b, $00, $a5, $24, $8b, $00, $a7, $22, $8b, $00, $a5, $1a, $8b, $00, $a7, $26, $8b, $00, $a5, $1d, $8b, $00, $a7
	db $22, $8b, $00, $a5, $1a
@song1ref631:
	db $8b, $00, $a7, $22, $8b, $00, $a5, $1b, $8b, $00, $a7, $1a
@song1ref643:
	db $8b, $00, $a5, $22, $8b, $00, $a7, $1a, $8b, $00, $a5, $1a, $8b, $00, $a7, $22, $8b, $00, $a5, $1d, $8b, $00, $a7, $22
	db $8b, $00, $a5, $18, $8b, $00, $a7, $22, $8b, $00, $a5, $1d, $8b, $00, $a7, $26, $8b, $00, $a5, $27, $8b, $00, $a7, $1a
	db $8b, $00, $a5, $26
	db $41, $13
	dw @song1ref631
	db $1d
	db $41, $0f
	dw @song1ref643
	db $41, $10
	dw @song1ref602
	db $1d
@song1ref706:
	db $8b, $00, $a5, $22, $8b, $00, $a7, $1a, $8b, $00, $a5, $1d, $8b, $00, $a7, $1a, $8b, $00, $a5, $18, $8b, $00, $a7, $26
	db $8b, $00, $a5, $1a, $8b, $00, $a7, $1d, $8b, $00, $a5, $22
@song1ref742:
	db $8b, $00, $a7, $26, $8b, $00, $a5, $26, $8b, $00, $a7, $26, $8b, $00, $a5, $1b
	db $41, $0f
	dw @song1ref742
	db $27, $8b, $00, $a7, $1d, $8b, $00, $a5, $22, $8b, $00, $a7, $22, $8b, $00, $a5, $24, $8b, $00, $a7, $1d, $8b, $00, $a5
	db $1a, $8b, $00, $a7, $26, $8b, $00, $a5, $1b, $8b, $00, $a7, $1a, $8b, $00, $a5, $1d, $8b, $00, $a7, $26, $8b, $00, $a5
	db $1b, $8b, $00, $a7, $26, $8b, $00, $a5, $1a, $8b, $00, $a7, $26
	db $41, $0f
	dw @song1ref706
	db $22
@song1ref826:
	db $8b, $00, $a5, $24, $8b, $00, $a7, $26, $8b, $00, $a5, $22
@song1ref838:
	db $8b, $00, $a7, $1d, $8b, $00, $a5, $26, $8b, $00, $a7, $1a, $8b, $00, $a5, $26, $8b, $00, $a7, $26
	db $41, $0f
	dw @song1ref826
	db $1a, $8b, $00, $a5, $1f
@song1ref866:
	db $8b, $00, $a7, $1a, $8b, $00, $a5, $22, $8b, $00, $a7, $1d, $8b, $00, $a5, $24, $8b, $00, $a7, $26, $8b, $00, $a5, $1a
	db $8b, $00, $a7, $26
	db $41, $13
	dw @song1ref643
	db $21, $8b, $00, $a7, $22, $8b, $00, $a5, $1a, $8b, $00, $a7, $1a, $8b, $00, $a5, $26
	db $41, $1b
	dw @song1ref866
	db $1a, $8b, $00, $a5, $26
	db $41, $0f
	dw @song1ref838
	db $21, $8b, $00, $dd, $42
	dw @song1ch2loop
@song1ch4:
@song1ch3:
@song1ch3loop:
@song1ref934:
	db $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db
	db $41, $10
	dw @song1ref934
	db $41, $10
	dw @song1ref934
	db $41, $10
	dw @song1ref934
	db $42
	dw @song1ch3loop
